# Generated by Django 4.2.6 on 2023-12-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=100)),
                ('vdiscription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childvc.vaccine')),
            ],
        ),
    ]
