# Generated by Django 4.2.6 on 2023-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0004_vaccine_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='vid',
        ),
        migrations.AlterField(
            model_name='faqs',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
