# Generated by Django 4.2.6 on 2023-12-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0005_remove_faqs_vid_alter_faqs_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childvc.vaccine'),
            preserve_default=False,
        ),
    ]
