# Generated by Django 4.2.5 on 2024-02-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0011_profile_delete_appointment_delete_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
