# Generated by Django 4.2.5 on 2024-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('1', 'P'), ('2', 'H')], default='1', max_length=20),
        ),
    ]
