# Generated by Django 4.2.5 on 2024-02-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0015_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vac',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='childvc.vaccine'),
            preserve_default=False,
        ),
    ]
