# Generated by Django 4.2.4 on 2024-02-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childvc', '0016_appointment_vac'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='vprice',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
