# Generated by Django 4.2.5 on 2024-02-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
